package com.cardinal.voca4j.api.album;

public enum TrackField {
	ARTIST, TRACKARTIST, FEATVOCALISTS, ID, LENGTHSECONDS, PRODUCERS, PUBLISHDATE, PV_ORIGINAL_NICONICODOUGA,
	PV_ORIGINAL_NOT_NICONICODOUGA, PV_REPRINT, TITLE, TITLE_EN, TITLE_ROMANIZED, TITLE_ORIGINAL, URL, VOCALISTS;
}
